import { Inter, Open_Sans } from 'next/font/google'
import './globals.css'


const inter = Inter({ subsets: ['latin'] })
const openSans = Open_Sans({
  subsets: ['latin'],
  weight: ['400'],
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={openSans.className}>
      <body className={inter.className}>{children}</body>
    </html>
  )
}
